### ISSUE TITLE
Doesn't show numbers fully and doesn't calculate till the number which was entered on input after that

### ISSUE THREAD

**Issue by udilbar** [malikabakhtiyorova/fizz-buzz#1]
![Screenshot_2](https://user-images.githubusercontent.com/68459485/98544850-680ce580-22b6-11eb-8ba0-16a4106c0957.png)

**Comment by udilbar** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/68459485/98545739-bbcbfe80-22b7-11eb-9b10-fbb236164d9a.png)
For example, when I wrote the number 2, it didn't show fizz-buzzs

**Comment by malikabakhtiyorova** [comment]
Done
